[project]
name = "DockBot"
version = "0.1.0"
description = ""
authors = ["Oisín Mc Laughlin"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "discord-py>=2.4.0",
    "requests>=2.32.3",
]
